###############
# ColorScheme #
###############
background_opacity 1
# BEGIN_KITTY_THEME
# Gruvbox Dark
include current-theme.conf
# END_KITTY_THEME

##########
# Fonts #
#########
font_size 13
# BEGIN_KITTY_FONTS
font_family      family="JetBrainsMono Nerd Font"
bold_font        auto
italic_font      auto
bold_italic_font auto
# END_KITTY_FONTS
undercurl_style thick-sparse

##########
# Cursor #
##########
cursor_blink_interval 1
cursor_trail 1
cursor_trail_decay 0.1 0.4
cursor_trail_start_threshold 2

#########
# Mouse #
#########
# url_color #fca7ea
url_style curly
open_url_with default
detect_urls yes
underline_hyperlinks hover

###########
# Tab Bar #
###########
tab_bar_edge top
tab_bar_margin_width 5
tab_bar_margin_height 5 0
tab_bar_min_tabs 2
tab_bar_style powerline
# Inactive tab (neutral gray tone)
tab_title_template "({index}) {tab.active_oldest_exe}"
# Active tab (highlighted accent)
active_tab_title_template "({index}) {tab.active_oldest_exe}"
active_tab_font_style bold

###################
# Advance Options #
###################
# Use system default shell
shell .
# Use system default editor
editor .
# Adjust clipboard max size
clipboard_max_size 1024
# Allow Hyprlinks
allow_hyprlinks yes
# Directly close the tab
confirm_os_window_close 0
# Allow remote access
single_instance yes
allow_remote_control yes

##########
# Window #
##########
# window_padding_width 2
# window_margin_width 2

################
# Keybindings #
###############
# Keyboard shortcuts.
kitty_mod alt+shift
map kitty_mod+t new_tab_with_cwd

# Move between tabs.
map alt+1 goto_tab 1
map alt+2 goto_tab 2
map alt+3 goto_tab 3
map alt+4 goto_tab 4
map alt+5 goto_tab 5
map alt+6 goto_tab 6
map alt+7 goto_tab 7
map alt+8 goto_tab 8
map alt+9 goto_tab 9

# Layout movement and settings.
map kitty_mod+k neighboring_window up
map kitty_mod+j neighboring_window down
map kitty_mod+h neighboring_window left
map kitty_mod+l neighboring_window right
map kitty_mod+, launch --location=default
map kitty_mod+q close_window


