# See: https://sw.kovidgoyal.net/kitty/kittens/quick-access-terminal/
line                      25
column                    80
edge                      top
background_opacity        0.85
hide_on_focus_loss        no
grab_keyword              no
margin_left               0
margin_right              0
margin_top                0
margin_bottom             0
focus_policy              exclusive
