# NOTE: Programs Submaps
bind = $mainMod, O, submap, programs
submap=programs

# Gnome Characters
bind = , E, exec, $submap_reset; $emoji

# Sound Controller
bind = , V, exec, $submap_reset; $terminal_float wiremix

# Waybar Killswitch
bind = , R, exec, $submap_reset; $waybar

# Open calculator
bind = , C, exec, $submap_reset; $calculator

# Hyprpicker: a color picker
bind = , P, exec, $submap_reset; $color_picker

# Gazelle: A wifi viewer
bind = , N, exec, $submap_reset; $terminal_float impala

# Btop: Task manager
bind = , T, exec, $submap_reset; $terminal_float btop

# Bluetooth manager
bind = , B, exec, $submap_reset; $terminal_float bluetui

# Adding submap escape button
bind= , escape, submap, reset
submap=reset

#  NOTE: Rofi Menu Submaps
bind = $mainMod, R, submap, rofi_menu
submap=rofi_menu
# Waybar Position
bind = , P, exec, $submap_reset; $script_dir/waybar-position.sh

# Change to Random wallpaper
bind = , W, exec, $submap_reset; $script_dir/wallpaper-switcher.sh

# Change Theme
bind = , T, exec, $submap_reset; $script_dir/theme-switcher.sh

# Power Menu Keybinding
bind = , L, exec, $submap_reset; $script_dir/layout-switcher.sh

# Kitty Sessionizer
bind = , S, exec, $submap_reset; $script_dir/kitty-sessionizer.sh

# Adding submap escape button
bind= , escape, submap, reset
submap=reset
