# See https://wiki.hypr.land/Configuring/Keywords/

# Default Settings variables
$terminal = kitty
$terminal_float = kitty --title float -e
$fileManager = thunar
$menu = killall rofi || rofi -show drun -location 0
$screenshotarea = hyprctl keyword animation "fadeOut,0,0,default"; grimblast --notify copysave area; hyprctl keyword animation "fadeOut,1,4,default"
$color_picker = hyprpicker -a -n

# Extra variables
$submap_reset=hyprctl dispatch submap reset
$script_dir=~/.config/hypr/scripts

# Main Mod Key
$mainMod = SUPER
$shiftMod = SUPER_SHIFT

# Theme Design Variables
$cursor_theme = Adwaita
$cursor_size  = 24

# Custom Application variable
$hyprpaper = killall hyprpaper && hyprctl dispatch exec hyprpaper
$calculator = killall gnome-calculator || hyprctl dispatch exec gnome-calculator
$waybar = killall waybar && hyprctl dispatch exec waybar
$emoji = killall gnome-characters || hyprctl dispatch exec gnome-characters
$browser = gtk-launch $(xdg-settings get default-web-browser)
