# -- Float Center for small applications -- #
windowrule {
  name = float_menu
  match:class = ^(nwg-look|timeshift-gtk|xdg-desktop-portal-gtk|com.github.hluk.copyq|org.pulseaudio.pavucontrol|net.davidotek.pupgui2|xarchiver)$

  float = on
  center = on
  animation = popin
}

# -- Kitty Terminal Float -- #
windowrule {
  name = kitty_float
  match:class = ^(kitty)$
  match:title = ^(float)$

  float = on
  center = on
  size = 900 700
  animation = popin
}

# -- Float Center all gnome apps -- #
windowrule {
  name = float_popup_for_gnome
  match:class = ^(.*org.gnome.*)$

  float = on
  center = on
  animation = popin
}

# -- Some gnome app exception -- #
windowrule {
  name = tile_rule_for_gnome
  match:class = ^(org.gnome.Evince)$

  tile = on
}

# -- Thunar Popup Float -- #
windowrule {
  name = thunar_popup_dialogues
  match:class = ^(thunar|Thunar)$
  match:title = ^(.*(File|Rename).*)$

  float = on
  center = on
  animation = popin
}

# -- Chromium Popup Dialogues -- #
windowrule {
  name = chromium_popup_dialogues
  match:class = ^(chromium)$
  match:title =^(Open|Save) File

  float = on
  center = on
  animation = popin
}

# -- Kitty float window -- #
windowrule {
  name = chromium_float_dialogues
  match:class = ^(kitty)$
  match:title =^(float)$

  float = on
  center = on
  animation = popin
}

# Ignore maximize requests from all apps. You'll probably like this.
windowrule {
  name = suppress-maximize-events
  match:class = .*

  suppress_event = maximize
}

# Fix some dragging issues with XWayland
windowrule {
  name = fix-xwayland-drags
  match:class = ^$
  match:title = ^$
  match:xwayland = true
  match:float = true
  match:fullscreen = false
  match:pin = false

  no_focus = true
}

# Hyprland-run windowrule
windowrule {
  name = move-hyprland-run
  match:class = hyprland-run

  move = 20 monitor_h-120
  float = yes
}

# -- Layer Rules -- #
# layerrule = blur, waybar
