##############
# Statusline #
##############

# Mode & messages
set -g mode-style "fg=#fabd2f,bg=#3c3836"

set -g message-style "fg=#fabd2f,bg=#3c3836"
set -g message-command-style "fg=#fabd2f,bg=#3c3836"

# Pane borders
set -g pane-border-style "fg=#3c3836"
set -g pane-active-border-style "fg=#fabd2f"

# Status bar
set -g status "on"
set -g status-justify "left"
set -g status-interval 5
set -g status-position bottom

set -g status-style "fg=#ebdbb2,bg=#282828"

set -g status-left-length "100"
set -g status-right-length "100"

set -g status-left-style NONE
set -g status-right-style NONE

# Use yellow for the left/right highlights
set -g status-left "#[fg=#282828,bg=#fabd2f,bold] #S #[fg=#fabd2f,bg=#282828,nobold,nounderscore,noitalics] "
set -g status-right "#[fg=#fabd2f,bg=#282828] #{prefix_highlight} #[fg=#fabd2f,bg=#3c3836] %Y-%m-%d #[fg=#282828,bg=#fabd2f,bold] #h "

# Window status
setw -g window-status-activity-style "underscore,fg=#fabd2f,bg=#282828"
setw -g window-status-separator " "

# Inactive windows
setw -g window-status-style "NONE,fg=#d79921,bg=#282828"
setw -g window-status-format "#[fg=#d79921,bg=#282828,bold] #I #W #F "

# Active window
setw -g window-status-current-style "NONE,fg=#fabd2f,bg=#3c3836"
setw -g window-status-current-format "#[fg=#fabd2f,bg=#3c3836,bold] #I #W #F "

# tmux-plugins/tmux-prefix-highlight support
set -g @prefix_highlight_output_prefix "#[fg=#fb4934]#[bg=#3c3836] "
set -g @prefix_highlight_output_suffix ""
