# set -g default-terminal "tmux-256color"
set -g default-terminal "xterm-256color"
#set -ga terminal-overrides ",*256col*:Tc"
set -ga terminal-overrides ",xterm-256color:Tc"

# Changing prefix keybinding
unbind C-b
set-option -g prefix C-t

# Reload config file
bind r source-file ~/.config/tmux/tmux.conf\; display "Config Reloaded!"

# split panes using | and -
bind | split-window -h
bind - split-window -v
unbind '"'
unbind %

# Enable mouse Support
set -g mouse on

# Moving window
bind-key -n C-M-Left swap-window -t -1 \; previous-window
bind-key -n C-M-Right swap-window -t +1 \; next-window

# Setting Vi Keybindings
set-window-option -g mode-keys vi

# vim-like pane switching
bind -r k select-pane -U 
bind -r j select-pane -D 
bind -r h select-pane -L 
bind -r l select-pane -R

# Resizing pane
bind -r C-k resize-pane -U 5
bind -r C-j resize-pane -D 5
bind -r C-h resize-pane -L 5
bind -r C-l resize-pane -R 5

# Start Pane from 1 instead of 0
set -g base-index 1

# Renumber windows on window close
set -g renumber-windows on

# Display lazygit
bind -r g display-popup -d '#{pane_current_path}' -w80% -h80% -E lazygit

# Tmux Sessionizer Script
bind-key -r f run-shell "tmux neww ~/.local/bin/tmux-sessionizer.sh"

# allow the title bar to adapt to whatever host you connect to
set -g set-titles on
set -g set-titles-string "#T"

# Import statusline
source ~/.config/tmux/statusline.conf

# import macos config
if-shell "uname -s | grep -q Darwin" "source ~/.config/tmux/macos.conf"

# Undercurl
set -as terminal-overrides ',*:Smulx=\E[4::%p1%dm'  # undercurl support
set -as terminal-overrides ',*:Setulc=\E[58::2::%p1%{65536}%/%d::%p1%{256}%/%{255}%&%d::%p1%{255}%&%d%;m'  # underscore colours - needs tmux-3.0

# Auto Install TPM
if "test ! -d ~/.tmux/plugins/tpm" \
   "run 'git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm && ~/.tmux/plugins/tpm/bin/install_plugins'"

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'tmux-plugins/tmux-prefix-highlight'
set -g @plugin 'sainnhe/tmux-fzf'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
