background_opacity         1
dynamic_background_opacity yes

# Cursor Style
cursor_blink_interval      1
cursor_trail               1

# Mouse Scrolling
pixel_scroll               yes
momentum_scroll            0.96
copy_on_select             yes

# URL Style
url_style                  curly
open_url_with              default
detect_urls                yes
underline_hyperlinks       hover
undercurl_style            thick-sparse

# Tab Bar
tab_powerline_style        angled
tab_bar_edge               bottom
tab_bar_style              powerline
tab_bar_min_tabs           2
tab_title_max_length       20
tab_bar_drag_threshold     5
tab_title_template         "({index}) {session_name + '/' + title if session_name else tab.active_oldest_exe}"
active_tab_title_template  "({index}) {session_name + '/' + title if session_name else tab.active_oldest_exe}"
active_tab_font_style      bold
