kitty_mod alt+shift
map kitty_mod+t new_tab_with_cwd

# Change font size
map kitty_mod+kp_subtract change_font_size all -2.0
map kitty_mod+kp_add change_font_size all +2.0
map kitty_mod+backspace change_font_size all 0

# Move between tabs.
map alt+1 goto_tab 1
map alt+2 goto_tab 2
map alt+3 goto_tab 3
map alt+4 goto_tab 4
map alt+5 goto_tab 5
map alt+6 goto_tab 6
map alt+7 goto_tab 7
map alt+8 goto_tab 8
map alt+9 goto_tab 9
map alt+0 goto_tab 10

# Layout movement and settings.
map kitty_mod+k neighboring_window up
map kitty_mod+j neighboring_window down
map kitty_mod+h neighboring_window left
map kitty_mod+l neighboring_window right
map kitty_mod+a>r combine : load_config_file : launch --type=background notify-send -u low "Kitty" "Config reloaded successfully!"

# Fix: Added a space after the key and wrapped the script in a shell call
map kitty_mod+d>d launch --type=os-window --cwd=current bash -c "~/.config/kitty/scripts/dev-session.sh"
