# Performance options
repaint_delay             10
input_delay               3
sync_to_monitor           yes

# Terminal Notification Options
enable_audio_bell         yes
visual_bell_duration      0.0
bell_on_tab               "󰂚"

# Os Specific tweaks
wayland_enable_ime        yes
