# Sync the refresh rate to monitor
sync_to_monitor         yes

# Set input delay (in milliseconds)
input_delay             3

# Set repaint delay (in milliseconds)
repaint_delay           10

# Setting up pixel scroll
pixel_scroll            yes

# Setting up momentum scroll
momentum_scroll         0.96

# Setting up drag threshold
drag_threshold          5
