# foot terminal configuration
# Location: ~/.config/foot/foot.ini
# Documentation: man foot.ini


include=${config_dir}/sections/main.ini
include=${config_dir}/sections/colors.ini
include=${config_dir}/sections/misc.ini
