[main]
# Shell to use (defaults to $SHELL)
#shell=/bin/bash

# Terminal type
term=xterm-256color

# Font configuration (fontconfig format)
font=JetBrainsMono Nerd Font:size=13
font-bold=JetBrainsMono Nerd Font:style=Bold:size=13
font-italic=JetBrainsMono Nerd Font:style=Italic:size=13
font-bold-italic=JetBrainsMono Nerd Font:style=Bold Italic:size=13

# Initial window size in characters (cols x rows)
# initial-window-size-chars=120x35

# Underline Thickness
underline-thickness=2px

# Setting up dpi config based on monitor size
dpi-aware=yes

# Window padding in pixels
pad=2x2

# Allow programs to resize the window
resize-by-cells=yes

# Locking window title
locked-title=no

# Word Delimiters
word-delimiters=,│`|:"'()[]{}<>
uppercase-regex-insert=yes
