[security]
# disabled|copy-enabled|paste-enabled|enabled
osc52=enabled

[scrollback]
lines=500
multiplier=3.0
indicator-position=none
# indicator-format=""

[tweak]
# Default: 512MB — reduce if RAM is tight
max-shm-pool-size-mb=128

[bell]
# Don't spawn notifications when window is focused
notify=no

[mouse]
# Tiny UX + render win
hide-when-typing=yes
