# Refer to the wiki for more information.
# https://wiki.hypr.land/Configuring/

# System Startup files #
source = ~/.config/hypr/hypr.d/startup.conf

# Monitors Settings #
source = ~/.config/hypr/hypr.d/monitors.conf

## Variables Section files ##
source = ~/.config/hypr/hypr.d/variables.conf

## Environment Variables ##
source = ~/.config/hypr/hypr.d/env.conf

## Input Settings ##
source = ~/.config/hypr/hypr.d/input.conf

## Graphics and design ##
source = ~/.config/hypr/hypr.d/look-n-feel.conf

## Graphics and design ##
source = ~/.config/hypr/hypr.d/layouts.conf

## Window Rules ##
source = ~/.config/hypr/hypr.d/window-rules.conf

# Keymaps # 
source = ~/.config/hypr/hypr.d/keymaps.conf

# Submaps #
source = ~/.config/hypr/hypr.d/submaps.conf

# Permission #
source = ~/.config/hypr/hypr.d/permission.conf

# Comment out this line if you don't want smart gaps #
# source = ~/.config/hypr/hypr.d/smart-gaps.conf
